# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_modules.ipynb (unless otherwise specified).

__all__ = ['foo']

# Cell
from nbdev_colab.core import *

# Cell
def foo(a, b):
  "Returns the sum"
  return a+b